# Generated by Django 4.1 on 2022-08-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Сфера деятельности')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_element', models.CharField(max_length=150, verbose_name='Описание элемента')),
                ('logotypes', models.ImageField(blank=True, upload_to='photos/', verbose_name='Логотип')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skills')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['id'],
            },
        ),
    ]
