# Generated by Django 4.1 on 2022-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_element_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=150, verbose_name='Информация')),
                ('icons', models.ImageField(blank=True, upload_to='photos/', verbose_name='Иконки')),
            ],
            options={
                'verbose_name': 'Инфа',
                'verbose_name_plural': 'Инфушечки',
                'ordering': ['id'],
            },
        ),
    ]
