# Generated by Django 4.1 on 2022-08-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='info',
            field=models.TextField(max_length=150, verbose_name='Информация'),
        ),
    ]
