# Generated by Django 4.1 on 2022-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_aboutme_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='info',
            field=models.TextField(max_length=200, verbose_name='Информация'),
        ),
    ]
