# Generated by Django 4.1 on 2022-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr', models.CharField(max_length=200, verbose_name='Ссылка на соцсеть')),
                ('media', models.ImageField(upload_to='photos/', verbose_name='Иконка соцсети')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='examples',
            name='pict',
            field=models.ImageField(upload_to='photos/', verbose_name='Картинги примеров работ'),
        ),
    ]
